### ISSUE TITLE
All Models need to be submitted 

### ISSUE THREAD

**Issue by freakysevenup** [PavanJakhu/People-of-Earth#10]
All models need to be submitted or procured so we can begin testing them.

Can we get the models in by February 12th?

**Comment by PavanJakhu** [comment]
What models do we have left?

**Comment by freakysevenup** [comment]
The mother ship for the aliens, a few different asteroid models, The passenger ship and model for a missile, a model for our laser.

**Comment by freakysevenup** [comment]
Alright, so I have found models for all of these, we still need the passenger ship to be delivered from our artist. I have found a backup for that model for now though, so this issue is technically closed. It would be nice to see that model sooner than later though. Chris if you can talk to the artist and let them know we are ready to receive it.

The music should be delivered very soon according to the musician, I am currently looking at free sources of music online though, as a backup in case he is not ready in time for the testing in the first week of March.
