### ISSUE TITLE
Shaders and far distances don't behave properly

### ISSUE THREAD

**Issue by PavanJakhu** [PavanJakhu/People-of-Earth#11]
Currently when you get away from objects (like the Earth) the shading for the lighting in the scene starts to give off a lot of artifacts. I don't really know how to solves this right now. Will have to look into proper lighting for large spaces.

**Comment by freakysevenup** [comment]
I have the strangest feeling that issue #22 and this issue are being caused by the same bug.

**Comment by freakysevenup** [comment]
New Branch off of develop called Re-Endering check it out, I found out why displayTexture wasn't working... however now that it kinda does, everything else rendered is broken. Except physics and projectiles and audio... Those all work fine still. 

Things that don't work anymore are:
Skybox, Models are inside out Lighting looks like it works, we just need the models to be right side out again to prove it.

**Comment by freakysevenup** [comment]
Also Alpha will likely be fixed when this is!! So hey @PavanJakhu you said you wanted smokey particles right??

**Comment by PavanJakhu** [comment]
Well I spent the last couple hours directly copying from Sibyl System and I'm like 95% sure it's the difference between GLM and PhsyX. The rendering and transform code is exactly the same besides how the math is accomplished.

I put it in Rendering-Dev at https://github.com/PavanJakhu/People-of-Earth/commit/8077054dd07fe5f104440c99123c1e2376ab7492.

**Comment by freakysevenup** [comment]
lol we think alike my friend, I was looking through Sibyl comparing line by line for hours trying to find what was different, and in the end we basically came to the same conclusion... We just may have to switch to PhysX... We'll collaborate tomorrow between classes,   and make a decision. If we decide to make the switch we should do it that night. and Just get it out of the way.

**Comment by freakysevenup** [comment]
This issue is essentially solved.
