### ISSUE TITLE
Skybox not Rendering Correctly

### ISSUE THREAD

**Issue by PavanJakhu** [PavanJakhu/People-of-Earth#19]
So I've been cracking away at the sky box but I can't figure out why it isn't rendering properly. You can see the result on the RenderingDev branch.

If @freakysevenup wants to work on this and I can work on #18, we can do that.

**Comment by freakysevenup** [comment]
Sounds good to me I'll start on this today.

**Comment by PavanJakhu** [comment]
Sync on the branch now, if you didn't. I added some comments to Skybox.

**Comment by freakysevenup** [comment]
I'll sync up in just a bit, currently cleaning the apartment.

Sent from my HTC

----- Reply message -----

**Comment by PavanJakhu** [comment]
We weren't passing the camera's view projection to GPU properly. Made a new method in the Camera3D.
