### ISSUE TITLE
Alpha doesn't work

### ISSUE THREAD

**Issue by freakysevenup** [PavanJakhu/People-of-Earth#22]
We can't use textures that have transparency, I have looked through Rendering Engine and I have attempted many different fixes for this but I can't seem to find the issue. Its not a necessity, but if we can fix this it would make some of our models look a lot better.

**Comment by freakysevenup** [comment]
Reworked rendering engine to use PhysX and we are currently trying to solve this issue.

**Comment by PavanJakhu** [comment]
Alpha doesn't work for other objects but it works for Particles (if they render) so the mission was accomplished nonetheless.
