### ISSUE TITLE
Music between menus

### ISSUE THREAD

**Issue by freakysevenup** [PavanJakhu/People-of-Earth#29]
When switching between menus music will suddenly stop from one menu scene, and sometimes begin before the next menu scene has even loaded. This bug is currently being traced, and a solution is in the works.

**Comment by PavanJakhu** [comment]
This has been fixed for awhile but now the InGame music doesn't update once the pause menu is pushed on top of the stack so the music doesn't switch anymore and just suddenly stops. I'm going to make it so when you push a scene it is going to keep track of what was enabled and what was playing and stops the music or continues to play it on a pop scene.

**Comment by PavanJakhu** [comment]
This got solved in #34.
