### ISSUE TITLE
"Press Start" Text Displayed after exiting options menu.

### ISSUE THREAD

**Issue by asidique** [PavanJakhu/People-of-Earth#38]
Severity:
Low

Description & Lead:
When you enter options, and then hit back, the "Press Start" text will appear again in front of the menu.

Build:
Midterm Demo

**Comment by PavanJakhu** [comment]
Fixed this in aa9a9b9e489714eca3112dd1ecc6e86e8ebcf3b0 when I was merging the main menu and the mission select screens.
