### ISSUE TITLE
GUI DynamicModule error

### ISSUE THREAD

**Issue by freakysevenup** [PavanJakhu/People-of-Earth#8]
CEGUI::DynamicModule(const class CEGUI::String &) (c:users/Pavan/Documents/CEGUI/cegui-0.8.4/cegui/src/DynamicModule.cpp:222)

This error is printed to the console upon running the test scene..

CEGUI seems to be linked improperly however when checked there appears to be no error in the linkage.

**Comment by freakysevenup** [comment]
We should have a Logger in this engine to help trace errors, I'm actually surprised we don't have one. I'll write one up this weekend, we can test it out next week.

**Comment by PavanJakhu** [comment]
Is this still a problem?

**Comment by freakysevenup** [comment]
This is no longer an issue
